csvconsumer/urls.py
from django.urls import path

from csvconsumer.views import CSVUploadFormProcessView,BaseFormTempalteView,CSVConsumerTaskStateView


urlpatterns = [
            path('',BaseFormTempalteView.as_view(),name="csv_upload_template"),
            path('upload/',CSVUploadFormProcessView.as_view(),name="csv_upload_consumer"),
            path('state/<str:task_id>/',CSVConsumerTaskStateView.as_view(),name="csv_upload_state"),
]

product/urls.py
from django.urls import path

from product.views import ProductListView,ProductDeleteAllView,ProductCreateView,ProductUpdateView

urlpatterns = [
    path('products/', ProductListView.as_view(), name='paginated-list'),
    path('delete/', ProductDeleteAllView.as_view(), name='delete'),
    path('product/create/', ProductCreateView.as_view(), name='create'),
    path('product/update/<slug:sku>/', ProductUpdateView.as_view(), name='update'),
]

webhook/urls.py
from django.urls import path

from webhook.views import WebhookModelFormsetView
urlpatterns = [
    path('webhook/config/', WebhookModelFormsetView.as_view(),name="webhook-config"),
]

webserver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('csvconsumer.urls','csvconsumer'),namespace="csvconsumer")),
    path('',include(('product.urls','product'),namespace="product")),
    path('',include(('webhook.urls','webhook'),namespace="webhook")),
]

product/models.py
import uuid
from django.db import models

# Create your models here.

class ProductModel(models.Model):
    uuid = models.UUIDField(editable=False,default=uuid.uuid4)
    name = models.CharField(max_length=256)
    sku  = models.SlugField(max_length=256,unique=True)
    active = models.BooleanField(default = False)
    description = models.TextField()


import django_tables2 as tables

class ProductModelTable(tables.Table):
    sku = tables.Column(attrs={'td': {'class': 'skucss'}})
    class Meta:
        model = ProductModel
        sequence = ('name', 'description', 'sku',"active")
        exclude = ("id","uuid")

webhook/models.py
from django.db import models

class WebhookModel(models.Model):
    url = models.URLField(max_length = 256) 
    on_create = models.BooleanField(default=False)
    on_update = models.BooleanField(default=False)

csvconsumer/forms.py
from django import forms


class CSVUploadForm(forms.Form):
    input_csv = forms.FileField()

product/forms.py
from django.forms import ModelForm
from product.models import ProductModel as Product


class ProductModelForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name","description","sku","active"]

csvconsumer/views.py
from django.shortcuts import render
from django.views.generic.edit import BaseFormView
from django.views.generic import TemplateView
from django.views.generic.edit import FormMixin
from django.views.generic import View
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse

from celery import current_app

from csvconsumer.forms import CSVUploadForm
from csvconsumer.tasks import process_csv

import json


class BaseFormTempalteView(FormMixin,TemplateView):
    http_method_names = ['get',]
    template_name = 'csvconsumer/upload_form.html'
    form_class = CSVUploadForm

class CSVUploadFormProcessView(BaseFormView):

    http_method_names = ['post',]
    form_class = CSVUploadForm
    success_url = '/products/'


    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        response = {'error':form.errors}
        return JsonResponse(response)

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        csvfile = self.request.FILES["input_csv"]
        fs = FileSystemStorage()
        filename = fs.save(csvfile.name, csvfile)
        uploaded_file_url = fs.url(filename)
        result = process_csv.delay(uploaded_file_url)
        response = {
                    "task_id":str(result.task_id),
                }
        return JsonResponse(response)

class CSVConsumerTaskStateView(View):
    """
        Grabs task ID from url to query for AsyncTask result
    """
    http_method_names = ['get',]

    def get(self, request, *args, **kwargs):
        url_task_id = kwargs["task_id"]
        task = current_app.AsyncResult(url_task_id)
        response = {
                    "task_id":task.id,
                    'state': task.state,
                    'details': task.info,
                }
        if task.status == 'SUCCESS':
            response['results'] = task.get()
        return JsonResponse(response)

product/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import ListView,View,CreateView,UpdateView

from product.models import ProductModel as Product, ProductModelTable
from product.filters import ProductFilter
from product.forms import ProductModelForm

from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django.db.models import Q

from webhook.signals import ping_webhook


class ProductListView(SingleTableMixin, FilterView):
    table_class = ProductModelTable 
    queryset = Product.objects.all()
    template_name = "product/list.html"
    filterset_class = ProductFilter


    def get_queryset(self,**kwargs):
        """Search for text in GET query"""
        queryset = super().get_queryset(**kwargs)
        q = self.request.GET.get('q')
        if q is not None and q != '':
            queryset = queryset.filter(
                Q(name__icontains=q) | Q(description__icontains=q)
            )
        return queryset 
    def get_context_data(self, **kwargs):
        """Send search query to context to fill in UI"""
        context = super().get_context_data(**kwargs)
        q = self.request.GET.get('q')
        context['search'] = q 
        return context



from django.shortcuts import redirect,reverse

class ProductDeleteAllView(View):
    http_allowed_methods = ['get']

    def get(self, request, *args, **kwargs):

        products = Product.objects.all()
        product_count = products.count()
        products.delete()
        messages.success(self.request, '{num} products deleted'.format(num=product_count))
        return redirect("/")


class ProductUpdateView(UpdateView):
    model = Product
    template_name = "product/model_form.html"
    success_url = "/products/"
    slug_field = 'sku'
    slug_url_kwarg = 'sku'
    form_class = ProductModelForm

    def form_valid(self, form):
        result = super().form_valid(form)
        """If the form is valid, fire create webhook."""
        product = self.get_object()
        messages.success(self.request, 'Product {sku} updated'.format(sku=product.sku))
        ping_webhook.send(sender=product.__class__,product_sku=product.sku,event_type="update")
        return result

class ProductCreateView(CreateView):
    model = Product
    template_name = "product/model_form.html"
    success_url = "/products/"
    slug_field = 'sku'
    slug_url_kwarg = 'sku'
    form_class = ProductModelForm

    def form_valid(self, form):
        result = super().form_valid(form)
        """If the form is valid, fire create webhook."""
        product = self.object
        messages.success(self.request, 'Product {sku} created'.format(sku=product.sku))
        ping_webhook.send(sender=product.__class__,product_sku=product.sku,event_type="create")
        return result

webhook/views.py
from django.shortcuts import render

from extra_views import ModelFormSetView
from webhook.models import WebhookModel
# Create your views here.


class WebhookModelFormsetView(ModelFormSetView):
    model = WebhookModel
    fields = ['url', 'on_create','on_update']
    template_name = 'webhook/formset.html'
    factory_kwargs = {'extra': 1}

csvconsumer/templates/csvconsumer/upload_form.html
{% extends 'base.html' %}
{% load static %}



{% block custom_js %}
     <script src="{% static 'js/app.js' %}"></script>
     <script src="{% static 'js/worker.js' %}"></script>
     <script src="{% static 'js/form_worker.js' %}"></script>
{% endblock %}

{% block content %}

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success messages {{ message.tags }}" role="alert">
        {{ message }}
    </div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
      </button>
    {% endfor %}
{% endif %}



<div class="row"> 
<form method="post" enctype="multipart/form-data" id="csv_upload_form">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <div class="row"> 
        <input id="upload-btn" type="submit" value="Upload" class="btn"> 
    </div>
</form>
</div>
<div class="row"> 

    <div id="task_id" style="display: none;" data-taskid=""></div>
</div>


<div class="modal fade" id="progressModal" tabindex="-1" role="dialog" aria-labelledby="progressModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="progressModalLabel">Uploading</h5>
      </div>
      <div class="modal-body">
        <div class="row"> 


        <table border = "1">
             <tr>
                <th>State</th>
                <th>Message</th>
                <th>Percentage</th>
             </tr>
              <tr>
                  <td ><div id="state">N/A</div></td>
                  <td ><div id="message">N/A</div></td>
                  <td ><div id="percentage_2">N/A</div></td>
             </tr>
        </table>
        </div>
        <div class="row w-100" > 
            <div class="progress">
              <div id="percentage" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>


      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

{% endblock %}

product/templates/product/list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load django_tables2 %}

{% block head %}
{% endblock %}

{% block custom_js %}
     <script src="{% static 'js/list.js' %}"></script>
{% endblock %}


{% block content %}

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success messages {{ message.tags }}" role="alert">
        {{ message }}
    </div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
      </button>
    {% endfor %}
{% endif %}

<div class="row"> 
{% if filter %}
    <form action="" method="get" class="form form-inline">
        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}

</div>

<div class="row"> 
{% render_table table 'django_tables2/bootstrap4.html' %}

</div>

{% endblock %}

product/templates/product/model_form.html
{% extends 'base.html' %}
{% load static %}


{% block custom_js %}
{% endblock %}


{% block content %}

<div class="row"> 

<form action="" method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <div class="row"> 
        <input type="submit" value="Submit">
    </div>
</form>
</div>

{% endblock %}

templates/base.html
{% load static %}


<html>
    <head>
        <title>Fulfil.io Test</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
       {% block head %}
        {% endblock %}
    </head>


    <body>
            {% include 'nav_bar.html' %}
        <div class="content container">
                    {% block content %}
                    {% endblock %}
        </div>
        <script>
            $('.alert').alert();
        </script>
        {% block custom_js %}
        {% endblock %}
	</body>

</html>

templates/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Fulfil.io</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/webhook/config/">Webhook Config</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Product
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url "product:create" %}">Add</a>
            <a class="dropdown-item" href="/">Upload CSV</a>
            <a class="dropdown-item" href="{% url "product:paginated-list" %}">List</a>
            <a class="dropdown-item" href="{% url "product:delete" %}">Delete All</a>
        </div>
      </li>
    </ul>
    <form id="search_form" action="{% url "product:paginated-list" %}" method="get" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name="q" placeholder="{% if search %} {{search}} {% else %}Search{% endif %}" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" form="search_form">Search</button>
    </form>
  </div>
</nav>

webhook/templates/webhook/formset.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block custom_js %}
    <script src="{% static 'js/django-dynamic-formset/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row-{{ formset.prefix }}').formset({
            addText: 'add another',
            deleteText: 'remove',
            prefix: '{{ formset.prefix }}',
        });
    </script>
{% endblock %}
{% block content %}


<form class="form-horizontal" method="POST" action="">
{% csrf_token %}
{{ formset.management_form|crispy }}
{% for form in formset %}
<div class="row form-row spacer formset_row-{{ formset.prefix }} ">
    <div class="row">
        <div class="col-2">
            <label>{{form.url.label}}</label>
        </div>
        <div class="col-4">
            <div class="input-group">
                {{form.url}}
            </div>
        </div>
    </div>
    </br>
    <div class="row">
        <div class="col-2">
            <label>{{form.on_create.label}}</label>
        </div>
        <div class="col-4">
            <div class="input-group">
                {{form.on_create}}
            </div>
        </div>
    </div>

    </br>
    <div class="row">
        <div class="col-2">
            <label>{{form.on_update.label}}</label>
        </div>
        <div class="col-4">
            <div class="input-group">
                {{form.on_update}}
            </div>
        </div>
    </div>


</div>
{% endfor %}


<div class="row spacer">
    <div class="col-4 offset-2">
        <button type="submit" class="btn btn-block btn-primary">Submit</button>
    </div>
</div>



{% endblock %}